//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortico.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityMaster
    {
        public int CityId { get; set; }
        public string CityName { get; set; }
        public int RefStateId { get; set; }
        public bool IsCityEnabled { get; set; }
    
        public virtual StateMaster StateMaster { get; set; }
    }
}
