//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortico.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exammaster
    {
        public int eid { get; set; }
        public string ename { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public string subjectname { get; set; }
        public string egroup { get; set; }
    }
}
