//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortico.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedbackmaster
    {
        public int fid { get; set; }
        public string fdesc { get; set; }
        public System.DateTime fdate { get; set; }
        public System.TimeSpan fitme { get; set; }
        public string femailid { get; set; }
    }
}
