//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortico.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentMaster
    {
        public int sid { get; set; }
        public string sname { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string emailid { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string image { get; set; }
        public string college { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string city { get; set; }
    }
}
